databases:
  - name: collabhub-db
    databaseName: collabhub
    user: collabhub
    plan: free

services:
  - type: web
    name: collabhub
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    preDeployCommand: "python manage.py migrate"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: collabhub-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.0

      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: project-collab-ovi8.onrender.com,.onrender.com
      - key: USE_S3
        value: False
      - key: SECURE_SSL_REDIRECT
        value: True
      - key: SESSION_COOKIE_SECURE
        value: True
      - key: CSRF_COOKIE_SECURE
        value: True
      - key: SECURE_HSTS_SECONDS
        value: 31536000
